// changelog.js - 从 git log 自动生成
const CHANGELOG = [
    {
        hash: 'dd10afd',
        date: '2026-06-21',
        title: 'feat: 添加start.sh启动脚本（自动更新日志）',
        stats: ' 1 file changed, 5 insertions(+)',
    },
    {
        hash: '0257bd8',
        date: '2026-06-21',
        title: 'feat: 更新日志改为自动从git log生成',
        stats: ' 3 files changed, 139 insertions(+), 59 deletions(-)',
    },
    {
        hash: '182e0e1',
        date: '2026-06-21',
        title: 'feat: 更新日志系统 - 主界面可查看历史更新内容',
        stats: ' 3 files changed, 87 insertions(+)',
    },
    {
        hash: '9ac4c22',
        date: '2026-06-21',
        title: 'feat: BOSS阶段视觉 + 场景交互机制(金锁柱/妒火祭坛/镜面碎片) + 修复NaN/pointer lock',
        stats: ' 4 files changed, 325 insertions(+), 7 deletions(-)',
    },
    {
        hash: '3ae9db0',
        date: '2026-06-21',
        title: 'feat: 战斗系统增强 - 三段连招+蓄力攻击+完美闪避+技能联动',
        stats: ' 141 files changed, 28789 insertions(+), 29 deletions(-)',
    },
    {
        hash: 'b2e814f',
        date: '2026-06-20',
        title: 'fix: 添加favicon链接标签，修复GitHub Pages 404',
        stats: ' 1 file changed, 1 insertion(+)',
    },
    {
        hash: '5089e0c',
        date: '2026-06-20',
        title: 'feat: 三BOSS阶段性战斗系统 + 按键残留修复 + 音频优化',
        stats: ' 6 files changed, 355 insertions(+), 70 deletions(-)',
    },
    {
        hash: '503817e',
        date: '2026-06-20',
        title: 'fix: 彻底去掉提示弹窗 + beginLevel reconfigure补回',
        stats: ' 1 file changed, 126 insertions(+), 22 deletions(-)',
    },
    {
        hash: 'a5ca1d9',
        date: '2026-06-20',
        title: 'feat: 第三关BGM重做 - 唢呐二胡太鼓 黑神话红楼梦风格',
        stats: ' 5 files changed, 385 insertions(+), 106 deletions(-)',
    },
    {
        hash: '80f6dc1',
        date: '2026-06-20',
        title: 'Revert "fix: 关卡选择BOSS正确切换 + 返回主界面按钮修复 + 去掉提示弹窗"',
        stats: ' 1 file changed, 10 insertions(+), 23 deletions(-)',
    },
    {
        hash: '64973fa',
        date: '2026-06-20',
        title: 'fix: 关卡选择BOSS正确切换 + 返回主界面按钮修复 + 去掉提示弹窗',
        stats: ' 1 file changed, 23 insertions(+), 10 deletions(-)',
    },
    {
        hash: 'e9a5c8d',
        date: '2026-06-20',
        title: 'feat: 三BOSS差异化重设计 + 关卡流转修复 + 返回主界面按钮',
        stats: ' 8 files changed, 1889 insertions(+), 346 deletions(-)',
    },
    {
        hash: '9f47cf4',
        date: '2026-06-20',
        title: 'cleanup: 移除多余脚本，BGM用MiniMax MP3，SFX用WebAudio',
        stats: ' 1 file changed, 126 deletions(-)',
    },
    {
        hash: 'd2f60ff',
        date: '2026-06-20',
        title: 'fix: BGM连续性+音效降低+剑气视觉重做',
        stats: ' 3 files changed, 77 insertions(+), 35 deletions(-)',
    },
    {
        hash: '7beaea6',
        date: '2026-06-20',
        title: 'v6: MiniMax真实BGM + UI布局优化(黑神话风格)',
        stats: ' 9 files changed, 162 insertions(+), 78 deletions(-)',
    },
    {
        hash: 'a655a56',
        date: '2026-06-20',
        title: 'v5: 模型重做+BGM修复+移动方向修复+呼吸动画',
        stats: ' 2 files changed, 3 insertions(+), 3 deletions(-)',
    },
    {
        hash: '19071dd',
        date: '2026-06-20',
        title: 'v4: 角色模型全面重做+走路呼吸动画+BGM修复',
        stats: ' 2 files changed, 428 insertions(+), 93 deletions(-)',
    },
    {
        hash: '4175107',
        date: '2026-06-20',
        title: 'fix: BGM初始化顺序 + .gitignore清理',
        stats: ' 1 file changed, 1 insertion(+)',
    },
    {
        hash: 'bd59b74',
        date: '2026-06-20',
        title: 'v3: 战斗手感+Boss AI+视觉改进+清理测试文件',
        stats: ' 1815 files changed, 6 insertions(+), 431655 deletions(-)',
    },
    {
        hash: '32402c8',
        date: '2026-06-20',
        title: '黑神话·林黛玉 v2 - 3关完整Demo + 视觉改进',
        stats: '',
    },
];
